version: '3.7'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
    command: yarn start:dev
    restart: always
    depends_on:
      - db
    env_file: ./.env
    ports: 
      - ${PORT}:${PORT}

  db:
    image: mongo
    container_name: database
    restart: always
    volumes:
      - mongodb_data:/data/db
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    command: mongod

  mongo-express:
    image: mongo-express
    container_name: db_tool
    restart: always
    env_file: ./.env
    ports:
      - ${EXPRESS_MONGO}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:{MONGO_PORT}
    depends_on:
      - db

volumes:
  mongodb_data:
