version: '3.7'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
    command: yarn start:dev
    restart: always
    depends_on:
      - db
    env_file: ./.env
    ports: 
      - ${PORT}:${PORT}

  db:
    image: mongo
    container_name: database
    restart: always
    volumes:
      - mongodb_data:/data/db
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    command: mongod

volumes:
  mongodb_data:
